### PR TITLE
Simplify preference filename configuration

### PR DESCRIPTION
**Pull request by trevordevore**
New syntax:

preferences:
  user:
    default: [optional default name]
    macos: [macos name]
    ios: [ios name]
    windows: [windows name]
    android: [android name]
  shared:
    [same as user]

### CODE REVIEW

**Comment by trevordevore** [comment]
@spencerlearning This PR changes the syntax for preferences to match the data folder syntax. I think we discussed making this change. Can you review and confirm?

**Comment by spencerlearning** [comment]
@trevordevore It looks good. The `app.yml` preferences section needs to be changed for this to work:

```
preferences:
  user:
    default:
    macos:
    windows:
    linux:
    ios:
    android:
  shared:
    default:
    macos:
    windows:
    linux:
```

**Comment by trevordevore** [comment]
@spencerlearning I've updated the app.yml file. Anything else?

**Comment by spencerlearning** [comment]
@trevordevore What do you think about making it `preferences filename:` instead of just `preferences:`.  "Preferences" is pretty vague for the new user (is it referring to a folder, a file name, default values?). Adding `filename` makes it clear.

Also,  a trivial thing, but you might consider moving `linux` below `windows` so the platform ordering is consistent with the `application data folder` section:

```
preferences filename:
  user:
    default:
    macos:
    windows:
    linux:
    ios:
    android:
```

If you make it `preferences filename` you will need to change the line in `prefFilenameForPlatform` from

```
put "preferences` into tA[1]
``` 

to

```
put "preferences filename` into tA[1]
```

**Comment by trevordevore** [comment]
@spencerlearning I agree with the "filename" addition. Done. I also reordered "linux". Any other thoughts before I merge?

**Comment by spencerlearning** [comment]
Everything looks good.

**Comment by trevordevore** [comment]
@macMikey FYI preferences syntax has changed in app.yml

**Comment by macMikey** [comment]
And just like that it goes from "what do you think" to boom.  done, before I can even say "yeah, I like 'preferences filename'"

**Comment by trevordevore** [comment]
Got to get to a 1.0 release :-)

**Pull request merged**
