### PR TITLE
Report error loading helper.yml files

### LINKED ISSUE #106: expandHelperAssetsFileReferenceArray silently chokes on invalid YAML files
If a helper has an invalid helper.yml file,  loadHelperConfigurationFile returns "Invalid YAML File", but then expandHelperAssetsFileReferenceArray doesn't do anything with that information.  It just skips the helper and moves on to the next one.  The result is that the helper doesn't load, but no error is thrown.

### PR DESCRIPTION
**Pull request by trevordevore**
Resolves #106

### CODE REVIEW

**Comment by macMikey** [comment]
Does not fix it.
A couple of things worth noting:
1) I don't see any code to report the error.  You added lines 2364 and 2365, which just cause the inner repeat to exit to the outer repeat, but that isn't any different than not adding the entry.  I don't see any code for actually reporting the error.  I think you would have to exit both repeats to make it to the point of reporting the error.
2) kVersion is still on 0.9.5.0, so verifying that the correct version is pulled involves a bit of sleuthing

**Comment by trevordevore** [comment]
@macMikey Oops. I've added an exit to the main repeat loop. Please try again. Regarding version - if you check out and use the branch for this PR (`tkd-report-helper-config-errors`) you are ensured you have the right version. Version number increases for the library as a whole aren't part of bugfix PRs.

**Comment by macMikey** [comment]
For the version, the only reason I made that comment is that you have 0.9.6 and 0.9.7 in the tags, but this version (and the ones further up) are still 0.9.5.
Anyway, yes, that fixes it.

**Comment by trevordevore** [comment]
Ah, so you are saying the Levure library version is out of sync with the tags. That makes more sense :-)

**Pull request merged**
